import pandas as pd
import random as rd
import datetime as dt
import smtplib

# SE ALGUMA COINCINDIR, SELECIONE ALEATORIAMENTE UM DOS ARQUIVOS TXT
# TROQUE [NOME] PELO NOME DA PESSOA
# ENVIE UM EMAIL COM A CARTA PARA CONTA DA PESSOA


# LER ARQUIVO CSV, COMPARAR TODAS AS DATAS 
